# table level details
dataset: "LAD_APR_2023_UK_NC"
table_description: Contains Local Authority District Name and Code as of April 2023
schema_version: 1
write_method: overwrite
partition_by: null
primary_key: LAD23CD
de_dupe_col: LAD23NM
table_tag: 
  Access Rights: INTERNAL - HMG only
  Contains Personal Identifiable Information: "no"
  DPIA Check Completed: "no"
  Essential Shared Data Assets Designation: "no" 
  Expected Data Update Frequency: Daily
  License required: "no"
  Publish to Data Catalogue: "no"
  Publish to National Data Library: "no"
  Reference Data: "no"
  Security Classification: OFFICIAL
  Theme: Geography

# column level details
schema:
  LAD23CD:
    target: local_authority_district_code_2023
    type: StringType
    description: Local Authority District Code for 2023
    tag: 
      - example_tag1
      - example_tag2
      
  LAD23NM:
    target: local_authority_district_name_2023
    type: StringType
    description: Local Authority District Name for 2023
    tag: null

# blanket permissions across all schemas; bronze, silver, gold - might need to rethink this
permissions:
  dev_role: 
    TST-SG-CDP-Core-DataEngineerD: "MANAGE"
  test_role: 
    TST-SG-CDP-Core-DataEngineer: "MANAGE"
  prod_role:
    PRD-SG-CDP-Core-DataEngineer: "MANAGE"

# this is currently used for the REST API params - do we want this here?
url: "https://services1.arcgis.com/ESMARspQHYMw9BZ9/arcgis/rest/services/"
params:
  where: "1=1"
  resultType: "standard"
  outFields: "LAD23CD,LAD23NM"
  returnIdsOnly: "false"
  returnUniqueIdsOnly: "false"
  returnCountOnly: "false"
  returnDistinctValues: "false"
  cacheHint: "false"
  sqlFormat: "none"
  f: "pjson"
